config/routes.rb
Taskapp::Application.routes.draw do

resources :projects
root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
		  redirect_to projects_path
		else
			render 'new'
		end
	end

	private 

	  def project_params
	  	params[:project].permit(:title)
	  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "logo.png" %>
<%= yield %>

<%= link_to "Home", projects_path %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
	<% @projects.each do |project| %>
	<li><%= link_to project.title, project_path(project.id) %></li>
	<% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= form_for @project do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>